---

- name: "Install {{ postgresql_package }}"
  ansible.builtin.pkgng:
    name: "{{ postgresql_package }}"
    state: present

- name: Install postgresql_extra_packages
  ansible.builtin.pkgng:
    name: "{{ postgresql_extra_packages }}"
    state: present

- name: "Install psycopg2"
  ansible.builtin.pkgng:
    name: databases/py-psycopg2
    state: present

- name: Enable postgresql
  ansible.builtin.service:
    name: "{{ postgresql_service }}"
    enabled: yes

- name: Create /etc/rc.conf.d/postgresql
  ansible.builtin.template:
    src: FreeBSD.rc.j2
    dest: /etc/rc.conf.d/postgresql
    validate: sh -n %s
    mode: "0644"
  notify:
    - Restart postgresql
