---

- name: Install postgresql_extra_packages
  pkgng:
    name: "{{ postgresql_extra_packages }}"
    state: present

- name: "Install {{ postgresql_package }}"
  pkgng:
    name: "{{ postgresql_package }}"
    state: present

- name: "Install psycopg2"
  pkgng:
    name: databases/py-psycopg2
    state: present

- name: Enable postgresql
  service:
    name: "{{ postgresql_service }}"
    enabled: yes

- name: Create /etc/rc.conf.d/postgresql
  template:
    src: FreeBSD.rc.j2
    dest: /etc/rc.conf.d/postgresql
    validate: sh -n %s
  notify:
    - Restart postgresql
