---

- name: Install postgresql_extra_packages
  openbsd_pkg:
    name: "{{ postgresql_extra_packages }}"
    state: present

- name: "Install {{ postgresql_package }}"
  openbsd_pkg:
    name: "{{ postgresql_package }}"
    state: present

- name: Enable postgresql
  service:
    name: "{{ postgresql_service }}"
    arguments: "{{ postgresql_flags }}"
    enabled: yes

- name: Run initdb
  command:
    cmd: "initdb {{ postgresql_initdb_flags }}"
    creates: "{{ postgresql_db_dir }}/base"
  become: yes
  become_user: "{{ postgresql_user }}"
