---
# tasks file for ansible-role-postgresql

- name: "Include vars/{{ ansible_os_family }}.yml"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include install-{{ ansible_os_family }}.yml"
  include: "install-{{ ansible_os_family }}.yml"

- name: Create postgresql.conf
  template:
    src: postgresql.conf.j2
    dest: "{{ postgresql_conf_file }}"
    mode: 0600
  notify: Restart postgresql

- name: Create pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: "{{ postgresql_pg_hba_conf_file }}"
    mode: 0600
  notify: Restart postgresql

- name: Start postgresql
  service:
    name: "{{ postgresql_service }}"
    state: started
