---
# tasks file for ansible-role-postgresql

- name: "Include vars/{{ ansible_os_family }}.yml"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include install-{{ ansible_os_family }}.yml"
  include: "install-{{ ansible_os_family }}.yml"

- name: Create postgresql.conf
  template:
    src: postgresql.conf.j2
    dest: "{{ postgresql_conf_file }}"
    mode: 0600
  notify: Restart postgresql

- name: Create pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: "{{ postgresql_pg_hba_conf_file }}"
    mode: 0600
  notify: Restart postgresql

- name: Start postgresql
  service:
    name: "{{ postgresql_service }}"
    state: started

- name: Create, delete, or modify postgresql_users
  postgresql_user:
    name: "{{ item.name }}"
    ca_cert: "{{ item.ca_cert | default(omit) }}"
    conn_limit: "{{ item.conn_limit | default(omit) }}"
    db: "{{ item.db | default(omit) }}"
    encrypted: "{{ item.encrypted | default(omit) }}"
    expires: "{{ item.expires | default(omit) }}"
    fail_on_user: "{{ item.fail_on_user | default(omit) }}"
    groups: "{{ item.groups | default(omit) }}"
    login_host: "{{ item.login_host | default(omit) }}"
    login_password: "{{ item.login_password | default(omit) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(omit) }}"
    login_user: "{{ item.login_user | default(omit) }}"
    no_password_changes: "{{ item.no_password_changes | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
    role_attr_flags: "{{ item.role_attr_flags | default(omit) }}"
    session_role: "{{ item.session_role | default(omit) }}"
    ssl_mode: "{{ item.ssl_mode | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
  become: yes
  become_user: "{{ postgresql_user }}"
  no_log: "{% if postgresql_debug %}no{% else %}yes{% endif %}"
  vars:
    ansible_ssh_pipelining: yes
  with_items: "{{ postgresql_users }}"
