---
name: Publish on Ansible Galaxy

on:
  push:
    tags:
      - "*.*.*"

jobs:
  publish:
    name: Publish on Ansible Galaxy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Release Ansible Role to Galaxy
        uses: hspaans/ansible-galaxy-action@v0.2.9
        with:
          # add GALAXY_API_KEY to repository secrets. the API key can be found
          # at:
          # https://galaxy.ansible.com/me/preferences
          api_key: ${{ secrets.galaxy_api_key }}
